FSWDFinalProject.UI.MVC/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FSWDFinalProject.Data.EF;

namespace FSWDFinalProject.UI.MVC.Controllers
{
    public class LocationsController : Controller
    {
        private FPResSysEntities db = new FPResSysEntities();

        // GET: Locations
        public ActionResult Index()
        {
            return View(db.Locations.ToList());
        }

        // GET: Locations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // GET: Locations/Create
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LocationId,LocationName,Address,City,State,ZipCode,ReservationLimit")] Location location)
        {
            if (ModelState.IsValid)
            {
                db.Locations.Add(location);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(location);
        }

        // GET: Locations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LocationId,LocationName,Address,City,State,ZipCode,ReservationLimit")] Location location)
        {
            if (ModelState.IsValid)
            {
                db.Entry(location).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(location);
        }

        // GET: Locations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Location location = db.Locations.Find(id);
            db.Locations.Remove(location);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FSWDFinalProject.UI.MVC/Controllers/UserAssetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FSWDFinalProject.Data.EF;
using FSWDFinalProject.UI.MVC.Utilities;
using Microsoft.AspNet.Identity;

namespace FSWDFinalProject.UI.MVC.Controllers
{
    public class UserAssetsController : Controller
    {
        private FPResSysEntities db = new FPResSysEntities();

        // GET: UserAssets
        public ActionResult Index()
        {
            var currentUser = User.Identity.GetUserId();
            if (User.IsInRole("Admin") || User.IsInRole("Franchise"))// If the user is an Admin they can see all records
            {
                var userAssets = db.UserAssets.Include(u => u.UserDetail);
                return View(userAssets.ToList());
            }
            else
            {
                var userAssets = (from o in db.UserAssets
                                  where o.UserId == currentUser
                                  select o).Include(u => u.UserDetail);
                return View(userAssets.ToList());
            }
        }

        // GET: UserAssets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserAsset userAsset = db.UserAssets.Find(id);
            if (userAsset == null)
            {
                return HttpNotFound();
            }
            return View(userAsset);
        }

        // GET: UserAssets/Create
        public ActionResult Create()
        {
            var currentUser = User.Identity.GetUserId();
            if (User.IsInRole("Admin") || User.IsInRole("Franchise"))
            {
                ViewBag.UserId = new SelectList(db.UserDetails, "UserId", "FullName");
            }
            else
            {
                var thisUser = from u in db.UserDetails
                               where u.UserId == currentUser
                               select u;

                ViewBag.UserId = new SelectList(thisUser, "UserId", "FullName");
            }
            return View();
        }

        // POST: UserAssets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserAssetId,AssetName,UserId,AssetPhoto,SpecialNotes,IsActive,DateAdded,AssetYear")] UserAsset userAsset, HttpPostedFileBase myImage)
        {
            if (ModelState.IsValid)
            {
                string imageName = "NoImage.png";
                if (myImage != null)
                {
                    //Get file extension - alternative to using a Substring() and IndexOf()
                    string imgExt = System.IO.Path.GetExtension(myImage.FileName);

                    //List of allowed extentions
                    string[] allowedExtensions = { ".png", ".gif", ".jpg", ".jpeg" };

                    if (allowedExtensions.Contains(imgExt))
                    {
                        //Use a GUID for saved file name on server
                        imageName = Guid.NewGuid() + imgExt;

                        //Create variables to pass to the ResizeImage method
                        //Signature for ResizingImage(savePath, fileName, image, maxImageSize, maxThumbSize)
                        string savePath = Server.MapPath("~/Content/img/CAI/");

                        Image convertedImage = Image.FromStream(myImage.InputStream);

                        int maxImageSize = 500;
                        int maxThumbSize = 100;

                        //Calling this method will use the variables created above to save the full size image and thumbnail image to your server.
                        UploadUtility.ResizeImage(savePath, imageName, convertedImage, maxImageSize, maxThumbSize);
                    }
                    userAsset.AssetPhoto = imageName;
                }
                string currentUserId = User.Identity.GetUserId();
                userAsset.UserId = currentUserId;
                userAsset.DateAdded = DateTime.Now;
                db.UserAssets.Add(userAsset);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.UserDetails, "UserId", "FirstName", userAsset.UserId);
            return View(userAsset);
        }

        // GET: UserAssets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserAsset userAsset = db.UserAssets.Find(id);
            if (userAsset == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.UserDetails, "UserId", "FirstName", userAsset.UserId);
            return View(userAsset);
        }

        // POST: UserAssets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserAssetId,AssetName,UserId,AssetPhoto,SpecialNotes,IsActive,DateAdded,AssetYear")] UserAsset userAsset)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userAsset).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.UserDetails, "UserId", "FirstName", userAsset.UserId);
            return View(userAsset);
        }

        // GET: UserAssets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserAsset userAsset = db.UserAssets.Find(id);
            if (userAsset == null)
            {
                return HttpNotFound();
            }
            return View(userAsset);
        }

        // POST: UserAssets/Delete/5
        [HttpPost, ActionName("Delete")]

        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserAsset userAsset = db.UserAssets.Find(id);
            db.UserAssets.Remove(userAsset);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FSWDFinalProject.UI.MVC/Controllers/UserDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FSWDFinalProject.Data.EF;
using Microsoft.AspNet.Identity;

namespace FSWDFinalProject.UI.MVC.Controllers
{
    public class UserDetailsController : Controller
    {
        private FPResSysEntities db = new FPResSysEntities();

        // GET: UserDetails
        public ActionResult Index()
        {
            var currentUser = User.Identity.GetUserId();
            if (User.IsInRole("Admin") || User.IsInRole("Franchise"))// If the user is an Admin they can see all records
            {
                var userDetails = db.UserDetails;
                return View(userDetails.ToList());
            }
            else
            {                               var userDetails = from o in db.UserDetails
                                  where o.UserId == currentUser
                                select o;
                return View(userDetails.ToList());
            }
            
        }

        // GET: UserDetails/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDetail userDetail = db.UserDetails.Find(id);
            if (userDetail == null)
            {
                return HttpNotFound();
            }
            return View(userDetail);
        }

        // GET: UserDetails/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,FirstName,LastName,UserPhone,LocationId")] UserDetail userDetail)
        {
            if (ModelState.IsValid)
            {
                db.UserDetails.Add(userDetail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userDetail);
        }

        // GET: UserDetails/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDetail userDetail = db.UserDetails.Find(id);
            if (userDetail == null)
            {
                return HttpNotFound();
            }
            return View(userDetail);
        }

        // POST: UserDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,FirstName,LastName,UserPhone,LocationId")] UserDetail userDetail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userDetail);
        }

        // GET: UserDetails/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDetail userDetail = db.UserDetails.Find(id);
            if (userDetail == null)
            {
                return HttpNotFound();
            }
            return View(userDetail);
        }

        // POST: UserDetails/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            UserDetail userDetail = db.UserDetails.Find(id);
            db.UserDetails.Remove(userDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FSWDFinalProject.UI.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        ThePitStop - Vehicle Detailing Service
    </title>

    <!-- Styles -->
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css" type="text/css" /><!-- Bootstrap -->
    <link rel="stylesheet" href="~/fonts/font-awesome/css/font-awesome.min.css" type="text/css" /><!-- Icons -->
    <link rel="stylesheet" href="~/fonts/themify-icons/themify-icons.css" type="text/css" /><!-- Icons -->
    <link rel="stylesheet" href="~/Content/css/owl.carousel.css" type="text/css" /><!-- Owl Carousal-->
    <link rel="stylesheet" href="~/Content/css/price-range.css" type="text/css" /><!-- Owl Carousal -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <link rel="stylesheet" href="~/Content/css/style.css" type="text/css" /><!-- Style -->
    <link rel="stylesheet" href="~/Content/css/responsive.css" type="text/css" /><!-- Responsive -->
    <link rel="stylesheet" href="~/Content/css/colors.css" type="text/css" /><!-- color -->
    <!-- REVOLUTION STYLE SHEETS -->
    <link rel="stylesheet" type="text/css" href="~/Scripts/js/rs-plugin/css/settings.css">
</head>
<body>
    <header class="simple-header for-sticky ">
        <!-- Top bar -->
        <div class="menu">
            <div class="container">
                <div class="logo">
                    <a href="index.html" title="">
                        <i class="fa fa-get-pocket"></i>
                        <span>The Pit Stop</span>
                        <strong>Vehicle Detailing Service</strong>
                    </a>
                </div><!-- LOGO -->

                <div class="popup-client">
                    <span>
                        <i class="fa fa-user"></i>@Html.Partial("_LoginPartial")
                    </span>
                </div>
                <span class="menu-toggle"><i class="fa fa-bars"></i></span>

                <nav>
                    <h1 class="nocontent outline">--- Main Navigation ---</h1>
                    <ul>
                        <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                        @*<li> @Html.ActionLink("Location", "Index", "Location")</li>*@
                        <li><a href="@Url.Action("Index", "Locations")">Locations</a></li>
                        <li><a href="@Url.Action("Contact", "Home")">Contact</a></li>

                        @if (User.IsInRole("Admin") || User.IsInRole("Franchise") || User.IsInRole("Client"))
                        {
                            <li><a href="@Url.Action("Index", "UserAssets")">Your Assets</a></li>
                            <li><a href="@Url.Action("Index", "UserDetails")">Account</a></li>
                            <li><a href="@Url.Action("Index", "Reservations")">Reservations</a></li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li><a href="@Url.Action("AdminMenu", "Home")">Admin Menu</a></li>
                        }
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <clear></clear>

    @RenderBody()

    <footer>
        <section class="top-line">
            <div style="background: url(../Content/img/footer.jpg) repeat scroll 50% 422.28px transparent;" class="parallax scrolly-invisible no-parallax blackish"></div><!-- PARALLAX BACKGROUND IMAGE -->
            <div class="container">
                <div class="row">

                    <div class="col-md-3 column">
                        <div class="about_widget widget">
                            <div class="heading1">
                                <h2><span>Useful</span> links</h2>
                            </div><!-- heading -->

                            <span><i class="fa fa-envelope"></i>clydeparkerwork@gmail.com</span>
                            <span><i class="fa fa-phone"></i>1+ 117-500-6191</span>
                            <span><i class="fa fa-location-arrow"></i><a href="#" title="">Find a Location near you</a></span>
                        </div>
                    </div>

                    <div class="col-md-3 column">
                        <div class="links_widget widget">
                            <div class="heading1">
                                <h2><span>Useful</span> links</h2>
                            </div><!-- heading -->
                            <ul>
                                <li><a href="#" title=""><i class="fa fa-angle-right"></i> Home</a></li>
                                <li><a href="#" title=""><i class="fa fa-angle-right"></i> About us</a></li>
                                <li><a href="#" title=""><i class="fa fa-angle-right"></i> Services</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <div class="bottom-line">
            <div class="container">
                <span>Copyright All Right Reserved 2021 <a href="#" title="">Clyde A. Parker</a></span>
            </div>
        </div>
        <a href="#" class="scrollToTop"><i class="ti ti-arrow-circle-up"></i></a>
    </footer>


    <!-- Script -->
    <script type="text/javascript" src="~/Scripts/js/modernizr.js"></script><!-- Modernizer -->
    <script type="text/javascript" src="~/Scripts/js/jquery-1.10.2.min.js"></script><!-- Jquery -->
    <script type="text/javascript" src="~/Scripts/js/bootstrap.min.js"></script><!-- Bootstrap -->
    <script type="text/javascript" src="~/Scripts/js/owl.carousel.min.js"></script><!-- Owl Carousal -->
    <script type="text/javascript" src="~/Scripts/js/html5lightbox.js"></script><!-- HTML -->
    <script type="text/javascript" src="~/Scripts/js/scrolly.js"></script><!-- Parallax -->
    <script type="text/javascript" src="~/Scripts/js/price-range.js"></script><!-- Parallax -->
    <script type="text/javascript" src="~/Scripts/js/script.js"></script><!-- Script -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script src="../Scripts/js/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
    <script src="../Scripts/js/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
    @RenderSection("Scripts", false)
    <script type="text/javascript">

        $(document).ready(function () {
            "use strict";
            jQuery('.tp-banner').show().revolution({
                dottedOverlay: "none",
                delay: 16000,
                startwidth: 1170,
                startheight: 700,
                hideThumbs: 200,
                thumbWidth: 100,
                thumbHeight: 50,
                thumbAmount: 5,
                navigationType: "bullet",
                navigationArrows: "solo",
                navigationStyle: "preview1",
                touchenabled: "on",
                onHoverStop: "on",
                swipe_velocity: 0.7,
                swipe_min_touches: 1,
                swipe_max_touches: 1,
                drag_block_vertical: false,
                parallax: "mouse",
                parallaxBgFreeze: "on",
                parallaxLevels: [7, 4, 3, 2, 5, 4, 3, 2, 1, 0],
                keyboardNavigation: "off",
                navigationHAlign: "center",
                navigationVAlign: "bottom",
                navigationHOffset: 0,
                navigationVOffset: 20,
                soloArrowLeftHalign: "left",
                soloArrowLeftValign: "center",
                soloArrowLeftHOffset: 20,
                soloArrowLeftVOffset: 0,
                soloArrowRightHalign: "right",
                soloArrowRightValign: "center",
                soloArrowRightHOffset: 20,
                soloArrowRightVOffset: 0,
                shadow: 0,
                fullWidth: "on",
                fullScreen: "off",
                spinner: "spinner4",
                stopLoop: "off",
                stopAfterLoops: -1,
                stopAtSlide: -1,
                shuffle: "off",
                autoHeight: "off",
                forceFullWidth: "off",
                hideThumbsOnMobile: "off",
                hideNavDelayOnMobile: 1500,
                hideBulletsOnMobile: "off",
                hideArrowsOnMobile: "off",
                hideThumbsUnderResolution: 0,
                hideSliderAtLimit: 0,
                hideCaptionAtLimit: 0,
                hideAllCaptionAtLilmit: 0,
                startWithSlide: 0,
                videoJsPath: "rs-plugin/videojs/",
                fullScreenOffsetContainer: ""
            });

            $(".carousel-prop").owlCarousel({
                autoplay: true,
                autoplayTimeout: 3000,
                smartSpeed: 2000,
                loop: true,
                dots: true,
                nav: false,
                items: 4,
                responsiveClass: true,
                responsive: {
                    0: {
                        items: 1,
                        nav: false
                    },
                    600: {
                        items: 2,
                        nav: false
                    },
                    1000: {
                        items: 3,
                        nav: true,
                        loop: false
                    }
                }
            });

            $(".carousel").owlCarousel({
                autoplay: true,
                autoplayTimeout: 3000,
                smartSpeed: 2000,
                loop: false,
                dots: false,
                nav: true,
                margin: 0,
                items: 3
            });

            $(".carousel-client").owlCarousel({
                autoplay: true,
                autoplayTimeout: 3000,
                smartSpeed: 2000,
                loop: false,
                dots: false,
                nav: true,
                margin: 30,
                items: 5,
                responsiveClass: true,
                responsive: {
                    0: {
                        items: 1,
                        nav: true
                    },
                    600: {
                        items: 3,
                        nav: true
                    },
                    1000: {
                        items: 5,
                        nav: true,
                        loop: false
                    }
                }
            });
        });
        $(function () {
            $("#datepicker").datepicker();
        });
    </script>
</body>

FSWDFinalProject.UI.MVC/Views/Shared/_OriginalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>